### ISSUE TITLE
unrecognized command-line option ‘-Qunused-arguments’

### ISSUE THREAD

**Issue by lanthora** [cwt-vf2/linux-cwt-starfive-vf2#3]
Thank you very much for your efforts.

I encountered a problem when compiling the kernel module.

```txt
make -C /lib/modules/5.15.2-cwt-3.7.5-1/build M=/root/hackernel/core/kernel-space modules
gcc: error: unrecognized command-line option ‘-Qunused-arguments’
make[2]: *** [scripts/Makefile.build:392: arch/riscv/kernel/vdso/vdso.lds] Error 1
make[1]: *** [arch/riscv/Makefile:124: vdso_prepare] Error 2
make: *** [Makefile:22: release] Error 2
```

It seems that it may also be related to https://github.com/cwt/pkgbuild-linux-cwt-starfive-visionfive2/issues/2.

**Comment by lanthora** [comment]
Compiling with clang can solve the above error.

```bash
make HOSTCC=clang CC=clang
```

I'd like to know why you choose to compile the kernel with clang instead of gcc

**Comment by cwt** [comment]
> I'd like to know why you choose to compile the kernel with clang instead of gcc

I really love llvm/clang, moreover clang on Arch and other distro like Fedora are multi-targets by default, so you can build RISC-V binary on x86_64 by just `clang --target=riscv64`.

Coincidently, I just make it able to build on any PC via podman before I read your issue. Please see this diff https://github.com/cwt/pkgbuild-linux-cwt-starfive-visionfive2/compare/9cd9a6b..1d52ea8

**Comment by lanthora** [comment]
thank you for your explanation.
