### ISSUE TITLE
Request new updates to be published in AUR

### ISSUE THREAD

**Issue by lanthora** [cwt-vf2/linux-cwt-starfive-vf2#4]
Now AUR has two packages about visionfive2(linux-515-starfive-visionfive2 and linux-515-starfive-visionfive2-headers), but they need to be compiled during installation.

Now updating the kernel requires manually downloading pkg.tar.zst and then pacman -U xxx.

If there is a bin package, upgrading will become very simple.

**Comment by cwt** [comment]
All RISC-V-only packages in AUR have been deleted, as it is clearly stated that the AUR is only for the officially supported architectures in Arch Linux which are i686 and x86_64.
